# Generated by Django 4.1.8 on 2023-04-12 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('received_date', models.DateField()),
                ('received_time', models.TimeField(blank=True)),
                ('ticket', models.CharField(blank=True, max_length=50)),
                ('eta', models.DateTimeField(blank=True)),
                ('comments', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='active', max_length=50)),
                ('type_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_api.typetask')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
